fix: don't retrieve ssm param if custom ami used
The ssm param for the recommended ami is not used if a custom ami is used.
Also, if one wishes to use a custom ami with the older AL2 ami_type (uses bootstrap.sh for user_data in launch templates),
retrieving the ssm param fails with k8s >= 1.33 due to the AL2 images being removed:

    Error: reading SSM Parameter (/aws/service/eks/optimized-ami/1.34/amazon-linux-2/recommended/image_id): couldn't find resource

Private-ref: https://tasks.opencraft.com/browse/BB-10631